apiVersion: v1
data:
  spring.datasource.password: dGVzdDEyMw==
  spring.datasource.url: amRiYzpteXNxbDovLzM1LjIyNy4xMC42MzozMzA2L3NwcmluZy10aHltZWxlYWY=
  spring.datasource.username: b3lpbg==
kind: Secret
metadata:
  creationTimestamp: "2024-03-23T08:32:42Z"
  name: app-secret
  namespace: app
  resourceVersion: "31518"
  uid: 8d7745f9-6b05-4984-85e5-91831431d8bd
type: Opaque
