apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitor
  annotations:
  # cert-manager.io/cluster-issuer: letsencrypt-nginx
spec:
  ingressClassName: nginx
  #tls:
 # - hosts:
 #   - monitor.oyintest.com
 #   secretName: monitor-tls

  rules:      
  - host: monitor.oyintest.com
    http:
      paths:
      - pathType: Prefix
        path: /mine
        backend:
          service:
            name: my-loki-stack-grafana
            port:
              number: 80
      - backend:
          service:
            name: my-prometheus-server
            port:
              number: 80
        path: /pro
        pathType: Prefix        
        
      
      
