apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dime
  annotations:
   cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  tls:
   - hosts: 
     - monitor.oyintest.com
     secretName: monitor-test-tls

  rules:
  - host: monitor.oyintest.com
    http:
      paths:
      - backend:
          service:
            name: argocd-server
            port:
              number: 443
        path: /argocd
        pathType: Prefix

      