---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: app-secret
  namespace: app
spec:
  encryptedData:
    spring.datasource.password: AgCz/hhzVIT7Oqy36h25fGHmyx2S7VuD0RE0MIz3qKncfFFyvQAGIwTANFfo7b3CIQxRiKhqxSLJu3CefHAcz1IvRvs3oueBuEvDHeCt8+7yeZVkcZ7X2GgWf1MccbYQvM6IdIrBGKZB1EqnBfZee0Ik3AMU6iVEJ56rpPrcWeh6UNqQicMADMSil5dVTvpVJA5XlLhuNheD29BtgVfJJm/HP69wq0kwjKhU6i8BNZ0ab15V29KVEeERAlDwGdEKZaHxr4XSbt9yCX5eyEjtEIAK0KaHOPbdCc/AiaTTYX/VZ6/bLfhLZyIMii4CJAtWvzbm6+7knB+QYSBbmGlnJKzv2YNpPybnkHiIzhSUa29ISNY19YUDoCQ8blpN0HAQo9WGglCBYBOhTeKg+/HVxvr0sSPMvwpivu5oQ/vCjtvC5R3A5noBqC2yrL4Mxnf9RpCyNhSMS4g/77UyE/zeL6pIP5qTcOsxODTKQnusA3y0Ms1i6fV5OOu1BZDAykUBgI3uEXZycIWdLLUTo81cOLyw9OWAG0T8py3ArF+G//iSinDUNLBcCrkTKF/Yn2ItjpnvDOUgSitP7P1+s72vcFJlCsMsHdAmy0PpXVDLfraQjPtpEYr00yG3DmGr2p2f+2onCtWKRKgRalwF7GFigvC9BGXrCUCaLqiBdLvUPor/7Eic8mtJ4J+S4K5lfVVWe749Y7NLoQMg
    spring.datasource.url: AgAAQesC5KLRcvzJue8rMWDhR4qbog5nYLZOnXoD/3zQ3P8tnJPan09J5+HmDCXygFBh7PR+WAk7EewtWImmXOvlSDY24w5zwoc27wS6GuJx4C3pi++cN9MEBEM+2kuOE3UpZMacluRSpkD9c4p2XjaF6yEyEg1xoiW+k/b7u0jdvdqDv3ogxErHEQEosXOA3vb2KCtR4Y20cC+93t6TWoyCIi+3m/Pkd47IApphRWdUhR7qrx1h9tWkUQ3CbSeOieJok6YoM7eIR/3JzcfRux4Z6lzOQLJt8i1+DPgVonJ+ZwkA6TLK4XkoR/YKSy/agq5ivQ2yPfETp8ZEXazQ94To5lX93VT6RCZ6oKQ8D9+iSVMsHJV02xQOd1Tl9DUHvZQwq23nF48Y5DOrfMh/ppdQhVX+48cwZCIq/Lo3JJ/F68kKgfhxFez1Zoo8FjOdjB5r4TsSjX7j/vvS0TmTkKlD6gtFgE+bI8OMQtF4vya7xndsm4b+Y2YkQPDS8hacZsjB8B8XeZqTmuHAOdMXBn9LA596zCytsu3VGlvFeB+NS7ajNmAXThMc3PcU66S7Qaj51rpY53RpQ8H0xe2PIj+qJmvf/k68lfu6O2IO2xEhIrsis0sxuELJagdZT8BgaoRrGQL/Bi56S38yRRAhS1OhdoJUu+C0pBmwstOf0NuBCsNFfJm3RX0sh9ljq5CkKg6dxOJKP9zIk/7bTG1YoLmQFj2EHM23JixwYI+StF6KFg/V5RhLcFiOkOY1wetOEA==
    spring.datasource.username: AgA5YKjzdcauuNBKRxdY/iC27rxPH0oK8xSOtrUh+O5HzNcS7JgJmvkatiJLVXQvQWU08u50gDCe63M4q6qEl9HI5qWNKXBgnxCcBH5V6GXq/O44bPmUUAHWO1Dw4br2+sSuB9AXDi1ylPj+cU/9YtlhjCRy0O84ZsmshCeOg8ZQrM/LNTu/bZzPReqnjSn4WNh/l/JMGFowgmMearCOL5DRqYoK8f+Jmzwq1X+RGyFfSroXjLA1/1zu0UvHk3ICC9O+sXZaS6XNQLAtG1hzwcjGjf7uAUTjrKiOhFjWStv6X8ObjkZJ/QN+K/RIalc6dQr4PWlQ3NQ0MOJ7pjZ27yr5ivA2efgFciPEMrO5LX6fvlz5yFkKNVRnEK4UlrVCY5iDkkwhINvp6VxaFLcqJ6CUtxWwgJBnl5Lv0ceP4pZ/1c8IsJZzzvqbuaDQWEMNo5wKaGxz4vKiMZmHo2xu5IbgpuEORiZ11Gtkxk/hMZ055T5NM4SrBNNd/8fLdohTVBjl8McJVn4rrwRetk2jSUraec4l5tp3yUDpE6AUT9kfHtAORBhysxG2RaONDHwHORJlpSNTg+V859IaagrSbGq4+mZ7dDOsmS09Hc5HXw5FK3qohLQ2DcEuzWLdyX+3BC+aB2LiBbO+xR98J86If9hdidmJ2lXghX1Zgl3PFFoXWxBGgzCYwY9G2XxVSBt5+smetJ6Y
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: app-secret
      namespace: app
    type: Opaque
