---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: app-secret
  namespace: app
spec:
  encryptedData:
    spring.datasource.password: AgC7D9oZskOZBtU9aVYbWnliBjWatq1t8sdM6uCmexVahjXy4gGlOKx7PsbfbDbn+9dR5VHgD03qC9I4/KzCU7jrrDyRQ1CadFXOJwDzD+5ykfGmLcmL5Pg9MibhGpGMmyY2xu91ROoJsAxBYAxh8M8wKK5RLmCw+v8wcWWbI+8z88MABEObi+0UXCVqP8nf0abvP6OMglSa8YQCGL+4nKynqWvDs/fMaqN1E1/PRNycQ5ciTH8neFBiG07dTVF0oajNRpqZbHlV2c6pVKMTRCDG49cmg02k42DGOe64skCyz6WdRSa0M0SNmOYO63YggAg02umiyeN5f0Nu1xhz5sSx10zlKa04i3SxomQRoWXoEpKwRghkMh/s9edXO/9CKpsEgScnJx58tW7c5Twmw9Q5XjeV+qfuTvoP8M0jATabosuajFFk9dkgKRp47s7eP+ZE1CRTr1VyOnmFf+VOfffKAzryK4W1XQx1vdPk3GNPRAKh+Bl6H4UFQUNaGTUgVw2gdhKbx/DO+024mvs6HF22uF746wOaTs72e6SNUXKL/9v9+MpuXfRxthtAsAPGlVdTaQ3R54jsD5P2kpGYbSVtKtCI23jUXY2AzTxThasMRn9XRILYvFBbzg3F1xDP3wfxiCGM5Dh2gzgGWWb7CfaJOvoERcpxw4OoB79m0WALcmfW/59333abauAjlhrgLo2P7p5OxCSq
    spring.datasource.url: AgBmBDSJ90YGz0EHrQ8ZprFa3KKtAA/43PgVR1CbbgSxJvyi32erm4NMJcxSLhL5e5/z9YwP8Yk63t97R5SX0PDMJ+YSwjrI8xPr9Xtag/hi1I3+IvnW2DQf530zzlTeQeCZXvzTU/F1QlIjduFxGsdBKDVa4jK5sb9+12/nXCV1oyij4ltQ+b3NA6AethmsxKrSfWR29Ouu/kAr1f2b29bSR1LZtU26F3dxZnzXRHeZRrrXEe/O5cHsDYjN7tP//zDGsBdMzLkZxQjQiNSxKCDzOA1YWqcs0puV8NwX2evt+yxG9JNanAIfmXDLk0Z59K0CtYWS2Whw+2kCR5AAN3wjO+5Wh5EReAzNzkvMydu3qbldnlxGFf4U166wuvt/0dGlTDIornVOWtJDchr5r0FYDX3pf0Ye8Xh5MNwyQhqyw8ldcLE7/tLu51Kt+aU+FUuqrvsuYEoQ7zzoiLfzqEgPjfKk8wcj1zzVCrc8nQuhZhO/eihoRzt3CTi/M/AwVzsPPuX2VksNDMDRxYB5fmawPhFWAh9UgNVntPjZtZ1ubfN64+aSV95/imGoHJSPfisUplwlG0kKMQVHR775HUqbLMA2aIrDpzOCIhafbZUIEdZw/9xV9vlxgVGZq8UPFEJulVhyILlADEAAL4jidsQId3hW8NpCtsD+G3locSUxT7wj4cEp7gMGAx8Wa+slRIb5ztZyNPDHOD69LqflS6CUJqfHJzpLu9SB1IvetuVshLNuiuIv2WA22scJvbm64w==
    spring.datasource.username: AgCjWmxTnEmZug+6wr2GyDUPYLkgAdi3Fz6HlIwQcq+cTeUT3wXeRR6iWGT8qFiD/AGXd4wVamQD2FoC4rlvueWTg6nkZW6E81HdOF5tVPgHC7NPaze5CFQuOMXS9bnrNcW/dQOA6bHWb3OBZBSsPZyD0HZyBa76AdxM22YIu4FApSIoWXKSIzzpuvWJy6n8TvsUbCzRZf0qze9BKeOF7k1u2VsOECewmEbQor1gI565qf78rLwOLlxAb+ZgkKqwuJxLMqQkqsDZN6eyKu45mJHO+/oFoBARJ9aamSl/JWEEk9vUwfuLtQL06GAvFA14iOWAAeiqRIdoR07GmT/5jL8bH4w+xyF/amPBpFONHTMG+7ZjNfYi/m1Bq8CUMsW1Ozh1k5qzudemMvDIOV8cqvECXR+/KkynwDm7Y3htgKK1j4d5rXfLx/aoQWeiH0viFnjSaI5gXmYq9YESJeucZD6z3jlVt9gRHGjZ1c5Wz/fOteplsn4o9qqroLatKia0SoJ8k/cIqY6ES9yuU4fe2i5DrdxeM0HAuJzfYbA4Z2G2GvmiDu01ao4DNvK6Fhm+hyOAXXO221fag0MD3gBg7Y8AwMP5NpkhsO6PG5Uqs10/OZBC93uY21q8nA0nk7RXGEO5BsbB/I6qlZzrFlF2KCFoj+FT3NP5N2/HppTc5FDo2m4Nc28BiJa6pidZ8MTXvY6pLffo
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: app-secret
      namespace: app
    type: Opaque
