---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: test-secret
  namespace: default
spec:
  encryptedData:
    spring.datasource.password: AgC5+5vkPoQkklMj4q/w3TuMYGPQoA58CcmPAgI7YImPLe9fo+k9/oylW21k983u3eXgWEPGwmY1z250UUCKJK2hZnbHVGhje0jP1Sgp+6VYGr27wKENqwihYECnYTzZ2A08lgDcZpCK/jMvw/ehD8s6wt7o5du17/JHPoip4gVuEaMnaWKBE+lqQ6G9+XNJAdeer1fOtF+uu7Dk3tUf2Yl7fPAlSaVd3pSZP0ODWSnJeZWfFPV81XXMScRIFWWOQQ1AstKAyygQ6r0bApuyUmF8paXzK5CxQZbDJZaUR7LkLn7mob3qvE8eJAKM9IIsHLdJsbAXZCDY5DcPCgZP7B+k3dcdWNO4orv+EZkRo8mennJfv5onu9u54XjSfC7pu3bPpDEUNs0VNtlcAbu46MVO3jRUJ++TghZTeb8l1A3Qc6RGyWcxakGvcff5lBt9up3nCa/tDHpQ68NKRBEaCfYsFs+lxSloax5fF0xbCjk+pG7u6gPZL6FkQXrA8Z7qGo1Nby+wLVob0Z+xauxjvbsvYy4GFLaNcZLylTxOHOyeiwpzHNgvsJ54daJhv3jDjQbs258jUsJVG0Cl1e06f+DPuObX0TUDAzdaYhZGaqnjSAY4q9sD+AHpnfdkvTASD5Qg7WOfdPqo5Y9EA0ex57znV5QRdP8MDWhzIDT+eRNxaNRD2b4sge9clQkQ4lbBHs1UDoG5c4tb
    spring.datasource.url: AgDLqliLc/6Vf4Y3tS4opp3+2vRH46BThazYJLESJqh5beHhrlBh/VbHYX/OFyVTo+bEo0CLTWZIIR9857mIR1YMBE8EjhdCbbJDEKBomzJFHHrKDjDIU6GCnXAbfRNDjH/9+s7c/wrj8pPvAfeLzuQWaZj+H9aMXjugFJbQxACVrAcxzz+IIc5EUS69clrhfnpEJqJm+Xto835Pn1uAGNeVIbZJqZTkee2QuglwhDrrPq1kDvqj2B36pkJuiKFjKcHs6QNz971hm+IEZrKkZTSugMGTAi7gcbUazmSVgiKRL/Zf3UO3eirvDhTZ3oNhXFG4OAnCTzxoBz2xgj3LXZ1IlrVbWYC73nVPZth8NVO3vLuRJLPZLqUsMP9t2hMFn7lwbo9k7rUXF+bwzuw0oBRXlg7JAIQJUlLzEKf/sIcYYCFdtdz35Uum37vLpyGTKtEjQwSbx3/w5FUczvT/I3WpEUQL8kjnw+/xu/7tEM4gRNEijcX9y6il3xNpELGlzs33aTZyScYwrz4NvvEuyaLHLnZ/eQlRROHGnMFL4newx7GLeDz02z1GeZEy9QmtdBdWlYMDVcXmMBJ5sE/URH8ws3oIcOZAqV7++1pK07rT02XSlQzqYujd3WzALf9vkbaLt0MX2INXI3F9+Ui/mKCJFGaJcCIT/W9Q0TT5qY7XkFUCizSBWjXQHRLJH9PPlby5arQFQH788jFaYayxEsEPrqnadH5BRKssc5iGVhyyNv+Or9JBBVOEoBpL4W40Pw==
    spring.datasource.username: AgAaibhhh3eKVkkEeWj80NL9Q3C97WuC23/MfiWV3pT9kFiizpSkT1Z94eB1pMZQjuUH5teVXlEcEXSuJu67nrx/RdTR70rrPP7RbEkOZj8GKcP9B/UV3/5dOREsIzWhEyFYkyn6/BaXUkKoxn1lAadWmCZCCdh8AaYrnNaW1IfD4GksNY+m39EFuJRLrdG7dpJzVrRB7Hf52VvQPd/lFmd3HH8hSuCwBy2f8ALkErnh1uHavlwmRjy4B4dzNl8SbkNOnbY5I0hfWAqApmvZ3E2hfG7KdFVs6FxkcRd0trKcfK80QGReoMp4RrBkGXurv9IAohzLWTqD4P4IMNFfE9+0Gvb7E+NmpVUf7FYvnOqSXZSUckHCWgxgkKxWoVBzVfGRl/8hN1N51Olhp1uwA60qBtYqM2+WIwFwAnjTYFwX8APlRsimXh9TcLmsOLEO8Y3mM546eZmVy87Qxz2HQak0zBALyCHeYIRTvYUEUqwp1fNwkSljiGCYZkUmJZvkiukYjKarJRnPsyOEjyxofv8zqJZyfE7OKoWqiyVX86LVIKzt5fTNmmjk7f3QsoqNMevyCMvzrUYRWvyodsdIMFemBf9XgQMRdC245cN+0XNGXg/vUoOItRxZvmMeNIfE150QOC10XNkNrsRVXMsAH+QfvCyQrZne2UVqLIWAKt09zs7v+T6+lNVu1K4XkQc1NOJXm56q
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: test-secret
      namespace: default
    type: Opaque
